"""Mapping between application sectors and external data source classifications."""

SECTOR_MAP = {
    "food_hospitality": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": True,
        "sijilat_activities": ["مطعم", "مقهى", "كافيتيريا", "تموين", "مخبز", "حلويات", "توريد أغذية"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": "Consumer Non-Cyclicals",
        "tamkeen_programs": ["enterprise_support", "training", "business_development"],
        "edb_focus": ["tourism", "food_processing"],
    },
    "real_estate": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "BX.KLT.DINV.CD.WD"],
        "cbb_relevant": True,
        "sijilat_activities": ["عقارات", "مقاولات", "بناء", "تشييد", "مواد بناء", "تطوير عقاري"],
        "trading_economics_sector": "GDP from Construction",
        "bourse_sector": "Real Estate",
        "tamkeen_programs": ["enterprise_support", "business_development"],
        "edb_focus": ["real_estate", "construction"],
    },
    "technology": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "IT.NET.USER.ZS", "IT.CEL.SETS.P2", "GB.XPD.RSDV.GD.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["برمجيات", "تقنية معلومات", "اتصالات", "حلول رقمية", "تطبيقات", "استشارات تقنية"],
        "trading_economics_sector": "GDP from Information and Communication",
        "bourse_sector": "Technology",
        "tamkeen_programs": ["enterprise_support", "training", "digital_transformation"],
        "edb_focus": ["ict", "fintech", "digital"],
    },
    "finance": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FM.LBL.BMNY.GD.ZS", "FP.CPI.TOTL.ZG", "BX.KLT.DINV.CD.WD"],
        "cbb_relevant": True,
        "sijilat_activities": ["خدمات مالية", "تأمين", "صرافة", "وساطة مالية", "استثمار"],
        "trading_economics_sector": "GDP from Financial Intermediation",
        "bourse_sector": "Financials",
        "tamkeen_programs": ["enterprise_support"],
        "edb_focus": ["financial_services", "islamic_finance", "fintech"],
    },
    "manufacturing": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "NV.IND.MANF.ZS", "NE.TRD.GNFS.ZS", "BX.KLT.DINV.CD.WD"],
        "cbb_relevant": False,
        "sijilat_activities": ["مصنع", "تصنيع", "إنتاج", "تعبئة", "تغليف"],
        "trading_economics_sector": "GDP from Manufacturing",
        "bourse_sector": "Industrials",
        "tamkeen_programs": ["enterprise_support", "export_support", "training"],
        "edb_focus": ["manufacturing", "logistics"],
    },
    "health": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "SH.XPD.CHEX.GD.ZS", "SP.POP.TOTL", "SH.MED.PHYS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["مستشفى", "عيادة", "صيدلية", "أجهزة طبية", "مستلزمات طبية", "رعاية صحية"],
        "trading_economics_sector": "GDP from Health and Social Work",
        "bourse_sector": "Healthcare",
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["healthcare"],
    },
    "education": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "SE.XPD.TOTL.GD.ZS", "SP.POP.TOTL", "SL.UEM.TOTL.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["مدرسة", "معهد", "تدريب", "تعليم", "حضانة", "دورات"],
        "trading_economics_sector": "GDP from Education",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training", "national_employment"],
        "edb_focus": ["education"],
    },
    "transport": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "IS.SHP.GOOD.TU", "NE.TRD.GNFS.ZS", "BX.KLT.DINV.CD.WD"],
        "cbb_relevant": False,
        "sijilat_activities": ["نقل", "شحن", "لوجستيات", "تخزين", "تخليص جمركي", "توصيل"],
        "trading_economics_sector": "GDP from Transport",
        "bourse_sector": "Industrials",
        "tamkeen_programs": ["enterprise_support", "export_support"],
        "edb_focus": ["logistics", "transport"],
    },
    "retail": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "NE.TRD.GNFS.ZS", "SP.POP.TOTL"],
        "cbb_relevant": True,
        "sijilat_activities": ["تجارة تجزئة", "تجارة جملة", "سوبرماركت", "متجر", "توزيع", "استيراد"],
        "trading_economics_sector": "GDP from Wholesale and Retail Trade",
        "bourse_sector": "Consumer Non-Cyclicals",
        "tamkeen_programs": ["enterprise_support", "training", "export_support"],
        "edb_focus": ["retail", "ecommerce"],
    },
    "ai_applications": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "IT.NET.USER.ZS", "IT.CEL.SETS.P2", "GB.XPD.RSDV.GD.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["ذكاء اصطناعي", "تعلم آلي", "تحليل بيانات", "أتمتة", "روبوتات", "برمجيات ذكية"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": "Technology",
        "tamkeen_programs": ["enterprise_support", "training", "digital_transformation"],
        "edb_focus": ["ict", "fintech", "digital"],
    },
    "energy_environment": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["طاقة شمسية", "طاقة متجددة", "إدارة نفايات", "معالجة مياه", "كفاءة طاقة", "بيئة"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": "Industrials",
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["manufacturing"],
    },
    "media_entertainment": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL"],
        "cbb_relevant": False,
        "sijilat_activities": ["إنتاج إعلامي", "ترفيه", "فعاليات", "تصوير", "بث", "محتوى رقمي"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["tourism"],
    },
    "agriculture": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["زراعة", "مزرعة", "أسماك", "ثروة حيوانية", "منتجات زراعية", "ألبان"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": "Consumer Non-Cyclicals",
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["food_processing"],
    },
    "professional_services": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "SL.UEM.TOTL.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["استشارات", "محاماة", "محاسبة", "ترجمة", "تصميم", "خدمات مهنية"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training", "business_development"],
        "edb_focus": ["financial_services"],
    },
    "tourism_travel": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["سياحة", "سفر", "وكالة سفر", "فنادق", "رحلات", "حجوزات"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["tourism"],
    },
    "sports_fitness": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL"],
        "cbb_relevant": False,
        "sijilat_activities": ["نادي رياضي", "لياقة بدنية", "تدريب رياضي", "معدات رياضية", "بطولات"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["tourism"],
    },
    "beauty_personal": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["صالون تجميل", "مستحضرات", "عناية شخصية", "عيادة تجميل", "مكياج"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
    "automotive": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["سيارات", "صيانة سيارات", "قطع غيار", "تأجير سيارات", "معرض سيارات"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
    "security_safety": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL"],
        "cbb_relevant": False,
        "sijilat_activities": ["حراسة أمنية", "أنظمة أمن", "مراقبة", "سلامة", "إنذار"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
    "cleaning_maintenance": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "SL.UEM.TOTL.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["تنظيف", "صيانة", "تعقيم", "خدمات نظافة", "صيانة مباني"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
    "events_weddings": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL"],
        "cbb_relevant": False,
        "sijilat_activities": ["تنظيم فعاليات", "أعراس", "حفلات", "قاعات", "مناسبات", "ديكور"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["tourism"],
    },
    "pet_services": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["عيادة بيطرية", "حيوانات أليفة", "أغذية حيوانات", "رعاية حيوانات"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
    "printing_packaging": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "NV.IND.MANF.ZS", "NE.TRD.GNFS.ZS"],
        "cbb_relevant": False,
        "sijilat_activities": ["طباعة", "مطبعة", "تغليف", "تصميم جرافيك", "هوية تجارية"],
        "trading_economics_sector": "GDP from Manufacturing",
        "bourse_sector": "Industrials",
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": ["manufacturing"],
    },
    "recycling_waste": {
        "worldbank_indicators": ["NY.GDP.MKTP.KD.ZG", "FP.CPI.TOTL.ZG", "SP.POP.TOTL"],
        "cbb_relevant": False,
        "sijilat_activities": ["إعادة تدوير", "نفايات", "خردة", "فرز", "تنظيف بيئي"],
        "trading_economics_sector": "GDP from Services",
        "bourse_sector": None,
        "tamkeen_programs": ["enterprise_support", "training"],
        "edb_focus": [],
    },
}
